"""Update gameNumInSeries and gamesInSeries column names of DodgerGames Table

Revision ID: 1da3fb0633cb
Revises: 6ab55ffdcb07
Create Date: 2023-11-06 21:39:24.891428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da3fb0633cb'
down_revision = '6ab55ffdcb07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('dodger_games', schema=None) as batch_op:
        batch_op.alter_column('gameNumInSeries', new_column_name='seriesGameNumber')
        batch_op.alter_column('gamesInSeries', new_column_name='seriesGameCount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('dodger_games', schema=None) as batch_op:
        batch_op.alter_column('seriesGameNumber', new_column_name='gameNumInSeries')
        batch_op.alter_column('seriesGameCount', new_column_name='gamesInSeries')

    # ### end Alembic commands ###
