"""Initial Migration

Revision ID: 3e22d5a4a6a6
Revises: 
Create Date: 2021-08-06 16:12:19.414733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e22d5a4a6a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    #? Generated by Alembic. May or may not adjustment so check!
    op.create_table('baseball_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_logo', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('city_name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'), #? Marks id as primary key, unique to all other rows
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('team_logo'),
    sa.UniqueConstraint('team_name')
    )
    op.create_table('dodger_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('gameNumInSeries', sa.Integer(), nullable=False),
    sa.Column('gamesInSeries', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['baseball_teams.id'], ), #? Sets up foreign key that uses ‘baseball_teams’ table with ‘id’ column
    sa.ForeignKeyConstraint(['home_team_id'], ['baseball_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=False),
    sa.Column('dodger_game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dodger_game_id'], ['dodger_games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    #? Alembic autogenerates instructions for it to follow if you want to rollback a migration
    #? Use `flask db downgrade` and you'll roll back by 1 (or add a num to the end to roll further back)
    op.drop_table('promos')
    op.drop_table('dodger_games')
    op.drop_table('baseball_teams')
    # ### end Alembic commands ###
